### ISSUE TITLE
Before and after installation iview UI 

### ISSUE THREAD

**Issue by 531431988** [nguyenvanduocit/vue-cli-plugin-style-resources-loader#10]
Before installation
![image](https://user-images.githubusercontent.com/8703951/53785963-15adea00-3f55-11e9-8521-0035a9da9804.png)

After installation
![image](https://user-images.githubusercontent.com/8703951/53786013-3bd38a00-3f55-11e9-94aa-831c60db5f3a.png)

**Comment by nguyenvanduocit** [comment]
It's because you're using scoped CSS.

**Comment by cotra** [comment]
reset in the independent .css file,not .vue file

**Comment by nguyenvanduocit** [comment]
Did you turned on css module config: https://vue-loader.vuejs.org/guide/css-modules.html
