### ISSUE TITLE
How To Import npm Dependencies?

### ISSUE THREAD

**Issue by smhmd** [nguyenvanduocit/vue-cli-plugin-style-resources-loader#12]
In a vue component to import an npm dependency in stylus you write:
 `@import '~open-color/open-color.styl'`
this is very literal and I don't know how to import open-color directly without specifying the path  (for example I don't know how to import nib in vue components)
but my question is how to import anything npm
```
const path = require('path');
module.exports = {
  pluginOptions: {
    'style-resources-loader': {
      preProcessor: 'stylus',
        patterns: [
          path.resolve(__dirname, '~open-color/open-color.styl')
        ],
      },
    },
};
```
doesn't work

**Comment by nguyenvanduocit** [comment]
patterns simply an absolute path, so you can try:

`path.resolve(__dirname, '.node_modules/open-color/open-color.styl')`
