### ISSUE TITLE
Cannot Add Loader 

### ISSUE THREAD

**Issue by cxgslegend** [nguyenvanduocit/vue-cli-plugin-style-resources-loader#14]
When I run "vue add style-resource-loader" it fails with the following message (I put in placeholder text for my user folder, but everything else is correct). 

ERROR  TypeError: Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at add (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\@vue\cli\lib\add.js:23:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by nguyenvanduocit** [comment]
Ưhat is your vue cli version?

**Comment by cxgslegend** [comment]
Sorry, it has taken me so long to respond (busy week at work). I have version 4.0.5.

**Comment by nguyenvanduocit** [comment]
Did you resolve the issue?

**Comment by cxgslegend** [comment]
No, I just kind of gave up.

**Comment by nguyenvanduocit** [comment]
My bad, I also can not reproduce the issue.
