### ISSUE TITLE
Plugin doesn't work if I remove style tag from App.vue component

### ISSUE THREAD

**Issue by Saabbir** [nguyenvanduocit/vue-cli-plugin-style-resources-loader#16]
![Screenshot_1](https://user-images.githubusercontent.com/10579433/77218852-0dbde980-6b5a-11ea-9e80-51dfdca7e2c2.png)

Can anyone please explain why is that?

**Comment by nguyenvanduocit** [comment]
I don't think this is a bug, the plugin's purpose is to import styles into every element's style, if your component doesn't have a style then the style-loader won't handle it and of course, the files you want to import will not be imported.
