### ISSUE TITLE
Support both scss and less in one project?

### ISSUE THREAD

**Issue by krave1986** [nguyenvanduocit/vue-cli-plugin-style-resources-loader#17]
Teams like to use different preprocessors.
We would like to reuse some styles defined in .scss and .less.

Is it possible to accomplish this?

I started my project via vue-cli and chosen less as the default one.
Here is my vue.config.js:
```
pluginOptions: {
    "style-resources-loader": {
      preProcessor: "less",
      patterns: [
        path.resolve(__dirname, "./src/styles/globals/*.less"),
        path.resolve(__dirname, "./src/styles/side-configuration/*.less"),
      ],
    },
  },
```

How should I add support for .scss?
If I understood correctly, value of preProcessor can only be string, right?

**Comment by nguyenvanduocit** [comment]
Correct, preProcessor is a string. In your case, I think you should use the style-resources-loader. https://www.npmjs.com/package/style-resources-loader
