### ISSUE TITLE
 How to find the cause of the error

### ISSUE THREAD

**Issue by zhangrunhao** [nguyenvanduocit/vue-cli-plugin-style-resources-loader#6]
hi,  my options is not wort, 
How to find the cause of the error?
this is my config.

```js
// vue.config.js
const path = require('path')

module.exports = {
  css: {
    loaderOptions: {
      css: {
        localIdentName: '[name]-[local]-[hash:5]',
        camelCase: 'only'
      },
    },
  },

  pluginOptions: {
    'style-resources-loader': {
      patterns: [path.resolve(__dirname, './src/style/index.stylus'),]
    }
  }
}
```

`yarn serve` is normal, no bug

**Comment by zhangrunhao** [comment]
![1544354922593_19_28_40__12_09_2018](https://user-images.githubusercontent.com/25164897/49696695-aab87580-fbe8-11e8-9dac-6ef4c6c7d790.jpg)

this is my catalog

**Comment by zhangrunhao** [comment]
if i delete vue.config.js . 
![1544356959331_20_02_37__12_09_2018](https://user-images.githubusercontent.com/25164897/49697038-6b405800-fbed-11e8-876a-36dab5f8c13f.jpg)
if i add vue.confog.js and to use default config
```js
module.exports = {
  pluginOptions: {
    'style-resources-loader': {
      preProcessor: 'stylus',
      patterns: []
    }
  }
}
```
what? loacl serve is noraml start.  but i have a error in only just...
to tell me a error about css-loader ?

**Comment by nguyenvanduocit** [comment]
Because the plugin need option 'style-resources-loader' to run. If you don't want to use the plugin anymore, please use command:
```
yarn remove vue-cli-plugin-style-resources-loader
```

**Comment by zhangrunhao** [comment]
OK, thank , do you have some method to find what's error happen? now, i don't have method to do init global style variable and function.

**Comment by nguyenvanduocit** [comment]
u can try to rename your file from .stylus to .styl

**Comment by zhangrunhao** [comment]
ok, thank, i will to try

**Comment by zhangrunhao** [comment]
> u can try to rename your file from .stylus to .styl

hi, now, Failed to compile.  Can you tell want can i do next to checkout my config or code.
![1544681262949_14_07_40__12_13_2018](https://user-images.githubusercontent.com/25164897/49919271-02085f80-fee1-11e8-9ed2-689eb04d4b7a.jpg)

**Comment by nguyenvanduocit** [comment]
Under "style-resources-loader", you should add one more option:
```
"preProcessor":"stylus"
```

**Comment by zhangrunhao** [comment]
> Under "style-resources-loader", you should add one more option:
> 
> ```
> "preProcessor":"stylus"
> ```

thank you , i figure out my problem.

**Comment by myst729** [comment]
> ```
> "preProcessor":"stylus"
> ```

Please add this to the doc.
