### ISSUE TITLE
Please support all options from style-resources-loader

### ISSUE THREAD

**Issue by laure-at-irun** [nguyenvanduocit/vue-cli-plugin-style-resources-loader#9]
The original [style-resources-loader](https://github.com/yenshih/style-resources-loader) supports multiple [options](https://github.com/yenshih/style-resources-loader#options). 

Please can you add the support of these options in the plugins options? 

For instance, with the injector option:

```javascript
module.exports = {
  pluginOptions: {
    'style-resources-loader': {
      'preProcessor': 'stylus',
      'patterns': [
        path.resolve(__dirname, './src/styles/abstracts/*.styl'),
      ], 
      injector: 'append',
    }
  }
}
```

Thanks in advance

**Comment by nguyenvanduocit** [comment]
Good idea, and it would better if you can help to contribute this feature.
